apiVersion: v1
data:
  index.php: |-
    <?php phpinfo(); ?>
kind: ConfigMap
metadata:
  name: php-index-file

---

apiVersion: v1
data:
  index.html: |-

    ciao mondo

kind: ConfigMap
metadata:
  name: index-html

---

apiVersion: v1
data:
  default.conf: |-
  
    server {
        listen       80;
        server_name  localhost;

        location / {
            root   /usr/share/nginx/html;
            index  index.php index.html index.htm;
        }

        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }

        # proxy the PHP scripts to Apache listening on 127.0.0.1:80
        #
        #location ~ \.php$ {
        #    proxy_pass   http://127.0.0.1;
        #}

        # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
        #
        location ~ \.php$ {
            fastcgi_pass   127.0.0.1:9000;
            fastcgi_index  index.php;
            fastcgi_param  SCRIPT_FILENAME  /var/www/html$fastcgi_script_name;
            include        fastcgi_params;
        }
    }

kind: ConfigMap
metadata:
  name: nginx-file
